# [Info]
site_name: 吴德志的个人网站 # 左上角标题
site_url: https://dezhi0730.github.io
site_author: 吴德志
site_description: 吴德志的个人网站

# [Navigtion]
nav:
  - 博客:
    - BLOG/index.md
    - BLOG/others.md
    - 代码:
      - BLOG/Apple/mac-recommend.md
      - BLOG/Apple/ipad-recommend.md
    - 科研:
      - BLOG/macOS/tree.md
      - BLOG/macOS/zoom.md
      - BLOG/macOS/sharing-mac-android.md
      - BLOG/macOS/mad.md
      - BLOG/macOS/stream.md
      - BLOG/macOS/intel-windows.md
    
  - 日记:
    - DIARY/index.md
    - '2023':
      - '12':
        - DIARY/2023/12/2023-12-25.md
    
  - 转载:
    - REPRODUCE/index.md
    - 演讲:
      - REPRODUCE/speech/tim-cook-at-duke.md
    - 摘录:
      - REPRODUCE/book/harford-occupation-choice.md
      - REPRODUCE/book/the-long-view.md
    - 文章:
      - REPRODUCE/article/proses.md
      - REPRODUCE/article/my-best-teacher.md
    - 博客:
      - REPRODUCE/blog/how-to-ask-questions-the-smart-way.md
    - 歌词:
      - REPRODUCE/lyrics/watagumo.md
    - 诗:
      - REPRODUCE/poem/poems.md
  - 网站:
    - WEBSITE/index.md # 访客打开网站第一个看到的是 docs/index.md（会报错 The following pages exist in the docs directory, but are not included in the "nav" configuration: index.md 不要紧）  如果访客之后想要重新看到这个界面  可以在 docs/WEBSITE/index.md 找到
    - WEBSITE/build.md
    - WEBSITE/help.md
    - WEBSITE/test.md
  - 随笔:
    - ESSAY/index.md
    - 随笔记:
      - ESSAY/Jottings/2311.md
      - ESSAY/Jottings/2310.md
      - ESSAY/Jottings/2309.md
      - ESSAY/Jottings/2308.md
      - ESSAY/Jottings/2307.md
      - ESSAY/Jottings/2306.md
      - ESSAY/Jottings/2305.md
      - ESSAY/Jottings/2304.md
      - ESSAY/Jottings/2303.md
      - ESSAY/Jottings/2302.md
      - ESSAY/Jottings/2301.md
      - ESSAY/Jottings/2211-2212.md
      - ESSAY/Jottings/2209-2210.md
      - ESSAY/Jottings/2207-2208.md
      - ESSAY/Jottings/2205-2206.md
      - ESSAY/Jottings/2203-2204.md
      - ESSAY/Jottings/2201-2202.md
      - ESSAY/Jottings/2111-2112.md
      - ESSAY/Jottings/2109-2110.md
      - ESSAY/Jottings/2107-2108.md
      - ESSAY/Jottings/2105-2106.md
      - ESSAY/Jottings/2103-2104.md
      - ESSAY/Jottings/2101-2102.md
      - ESSAY/Jottings/2011-2012.md
      - ESSAY/Jottings/2009-2010.md
      - ESSAY/Jottings/2007-2008.md
      - ESSAY/Jottings/2005-2006.md
      - ESSAY/Jottings/2003-2004.md
      - ESSAY/Jottings/2001-2002.md
      - ESSAY/Jottings/0.md
      - ESSAY/Jottings/1906-1912.md
      - ESSAY/Jottings/1807-1812.md
      - ESSAY/Jottings/1801-1806.md
      - ESSAY/Jottings/17.md
      - ESSAY/Jottings/16.md
    - 文章:
      - ESSAY/Articles/231211-life-targets.md
      - ESSAY/Articles/231018-research.md
      - ESSAY/Articles/230629-account-book.md
      - ESSAY/Articles/230403-buy-phone.md
      - ESSAY/Articles/230305-cccc-memory.md
      - ESSAY/Articles/221227-expressvpn-refund.md
      - ESSAY/Articles/220921-upgrade-introduction.md
      - ESSAY/Articles/220715-macbook-story.md
      - ESSAY/Articles/220624-gratitude.md
      - ESSAY/Articles/220621-bytedance-interview.md
      - ESSAY/Articles/220612-reply.md
      - ESSAY/Articles/2205-good-games.md
      - ESSAY/Articles/220506-stop-jianshu.md
      - ESSAY/Articles/220505-library-thu.md
      - ESSAY/Articles/220415-interestx2.md
      - ESSAY/Articles/220410-job-discussion.md
      - ESSAY/Articles/220410-independence.md
      - ESSAY/Articles/220408-appreciating-girl.md
      - ESSAY/Articles/220402-languages-comparision.md
      - ESSAY/Articles/220324-thoughts-996.md
      - ESSAY/Articles/220107-want-to-be.md
      - ESSAY/Articles/211104-emotion-bad.md
      - ESSAY/Articles/210928-apple-recruitment-share.md
      - ESSAY/Articles/2109-covid-influence.md
      - ESSAY/Articles/2109-group-clear.md
      - ESSAY/Articles/210820-cccc-event.md
      - ESSAY/Articles/210801-affection-3.md
      - ESSAY/Articles/210519-app-dev-experience.md
      - ESSAY/Articles/210516-apple-education-address.md
      - ESSAY/Articles/210502-extend-your-way.md
      - ESSAY/Articles/201119-a-new-review.md
      - ESSAY/Articles/201213-look-at-yourself.md
      - ESSAY/Articles/200916-my-pursue.md
      - ESSAY/Articles/200713-sutuo-and-me.md
      - ESSAY/Articles/200703-talk-with-junior.md
      - ESSAY/Articles/200607-gaokao-memory.md
      - ESSAY/Articles/200604-small-goal.md
      - ESSAY/Articles/200602-tennkinoko.md
      - ESSAY/Articles/200506-why.md
      - ESSAY/Articles/2005-travel.md
      - ESSAY/Articles/190730-tangyan-rd-23.md
      - ESSAY/Articles/190723-feelings-in-6-days.md
      - ESSAY/Articles/190707-address-to-nonlocal-students.md
      - ESSAY/Articles/190629-affection-2.md
      - ESSAY/Articles/1905-non-intelligent.md
      - ESSAY/Articles/1901-go-to-thu.md
      - ESSAY/Articles/1811-do-it.md
      - ESSAY/Articles/1808-ideality-and-reality.md
      - ESSAY/Articles/1806-apply-thu.md
      - ESSAY/Articles/18-tree.md
      - ESSAY/Articles/18-what-i-love.md
      - ESSAY/Articles/17-dream-2017.md
      - ESSAY/Articles/14-affection-1.md
  - 我:
    - ME/index.md
    - ME/introduction.md
    - ME/profile.md
    - ME/contact.md
    - ME/account.md
    - ME/description.md
    - ME/ability.md
    - ME/experience.md
    - ME/thu-curriculum.md
    - ME/thu-certificate.md
    - ME/daily-necessities.md
    - ME/girlfriend.md
    - ME/support.md

# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/dezhi0730/dezhi0730.github.io # 右上角点击跳转的链接
repo_name: dezhi0730.github.io # 右上角的名字
## [bottom-left corner]
copyright: 吴德志 CC-BY-4.0 # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/dezhi0730
      name: GitHub | dezhi0730

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # 数学公式支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_javascript:
  # 数学公式支持
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - mkdocs/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols

extra:
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

extra:
  analytics:
    provider: google
    property: G-FRXE6S07X4