name: publish site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0 # 使用具体的次版本
      - uses: actions/setup-python@v2.4.0
        with:
          python-version: '3.9' # 指定具体的Python版本
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
